version: '3.9'
volumes:
  minio:
services:
  minio:
    image: minio/minio:latest
    container_name: object-storage
    ports:
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    entrypoint: sh
    command: -c "
      mkdir -p /data/.minio.sys/buckets;
      cp -r /policies/* /data/.minio.sys/;
      cp -r /export/* /data/;
      /opt/bin/minio server --console-address ":9001" /data;
      "
    volumes:
      - minio:/data
      - ./docker/minio/export:/export
      - ./docker/minio/policies:/policies